export const FETCH_ALL_ARTICLE = 'xmm/index/FETCH_ALL_ARTICLE';
export const FETCH_ALL_ARTICLE_SUCCESS = 'xmm/index/FETCH_ALL_ARTICLE_SUCCESS';
export const FETCH_ALL_ARTICLE_ERROR = 'xmm/index/FETCH_ALL_ARTICLE_ERROR';
