export const FETCH_ARTICLE_CONTENT = 'xmm/article/FETCH_ARTICLE_CONTENT';
export const FETCH_ARTICLE_CONTENT_SUCCESS = 'xmm/article/FETCH_ARTICLE_CONTENT_SUCCESS';
export const FETCH_ARTICLE_CONTENT_ERROR = 'xmm/article/FETCH_ARTICLE_CONTENT_ERROR';

export const CHANGE_CURRENT_ARTICLE = 'xmm/article/CHANGE_CURRENT_ARTICLE';
