export const CHANGE_ARTICLE_INFO = 'xmm/admin/CHANGE_ARTICLE_INFO';

export const PUSH_ARTICLE = 'xmm/admin/PUSH_ARTICLE';
export const PUSH_ARTICLE_SUCCESS = 'xmm/admin/PUSH_ARTICLE_SUCCESS';
export const PUSH_ARTICLE_ERROR = 'xmm/admin/PUSH_ARTICLE_ERROR';

export const FETCH_PRIVATE_ARTICLE = 'xmm/admin/FETCH_PRIVATE_ARTICLE';
export const CHANGE_PRIVATE_ARTICLE = 'xmm/admin/CHANGE_PRIVATE_ARTICLE';

export const CHANGE_HIGHLIGHT_CURRENT = 'xmm/admin/CHANGE_HIGHLIGHT_CURRENT';

export const FETCH_EDITED_ARTICLE = 'xmm/admin/FETCH_EDITED_ARTICLE';
export const FETCH_EDITED_ARTICLE_SUCCESS = 'xmm/admin/FETCH_EDITED_ARTICLE_SUCCESS';
